-- CLEAN SCRUB BUSINESS ADMIN UPGRADE
-- Run once in Supabase SQL Editor AFTER the admin security and receipt setup.

-- 1) Expenses
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  expense_date date not null default current_date,
  description text not null,
  category text not null,
  amount numeric(10,2) not null check (amount >= 0),
  created_at timestamptz not null default now()
);

alter table public.expenses enable row level security;

grant select, insert, update, delete on table public.expenses to authenticated;
grant usage, select on sequence public.expenses_id_seq to authenticated;

drop policy if exists "Admins can view expenses" on public.expenses;
drop policy if exists "Admins can create expenses" on public.expenses;
drop policy if exists "Admins can update expenses" on public.expenses;
drop policy if exists "Admins can delete expenses" on public.expenses;

create policy "Admins can view expenses"
on public.expenses for select to authenticated
using (public.is_clean_scrub_admin());

create policy "Admins can create expenses"
on public.expenses for insert to authenticated
with check (public.is_clean_scrub_admin());

create policy "Admins can update expenses"
on public.expenses for update to authenticated
using (public.is_clean_scrub_admin())
with check (public.is_clean_scrub_admin());

create policy "Admins can delete expenses"
on public.expenses for delete to authenticated
using (public.is_clean_scrub_admin());

-- 2) Make sure signed-in admin can manually create bookings
grant insert on table public.bookings to authenticated;

drop policy if exists "Admins can create manual bookings" on public.bookings;
create policy "Admins can create manual bookings"
on public.bookings for insert to authenticated
with check (public.is_clean_scrub_admin());

-- 3) Allow cancelled appointments to free the slot.
-- Remove the original all-status unique constraint if it exists.
alter table public.bookings
drop constraint if exists unique_booking_slot;

drop index if exists public.unique_active_booking_slot;

-- Only active bookings reserve a slot. A Cancelled booking no longer blocks it.
create unique index unique_active_booking_slot
on public.bookings (booking_date, booking_time)
where coalesce(status, 'Pending') <> 'Cancelled';
