-- CLEAN SCRUB RECEIPT SYSTEM - run once in Supabase SQL Editor
create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  booking_id bigint not null unique references public.bookings(id) on delete restrict,
  receipt_number text unique,
  customer_name text not null,
  phone text,
  service text not null,
  amount numeric(10,2) not null check (amount >= 0),
  payment_method text not null check (payment_method in ('Cash','EFT')),
  payment_status text not null default 'Paid' check (payment_status in ('Paid','Unpaid')),
  note text,
  created_at timestamptz not null default now()
);
create sequence if not exists public.clean_scrub_receipt_seq start 1;
create or replace function public.set_clean_scrub_receipt_number()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 if new.receipt_number is null then new.receipt_number := 'CS-' || lpad(nextval('public.clean_scrub_receipt_seq')::text,4,'0'); end if;
 return new;
end; $$;
drop trigger if exists trg_clean_scrub_receipt_number on public.receipts;
create trigger trg_clean_scrub_receipt_number before insert on public.receipts for each row execute function public.set_clean_scrub_receipt_number();
alter table public.receipts enable row level security;
grant select,insert,update on table public.receipts to authenticated;
grant usage,select on sequence public.receipts_id_seq to authenticated;
grant usage,select on sequence public.clean_scrub_receipt_seq to authenticated;
drop policy if exists "Admins can view receipts" on public.receipts;
drop policy if exists "Admins can create receipts" on public.receipts;
drop policy if exists "Admins can update receipts" on public.receipts;
create policy "Admins can view receipts" on public.receipts for select to authenticated using(public.is_clean_scrub_admin());
create policy "Admins can create receipts" on public.receipts for insert to authenticated with check(public.is_clean_scrub_admin());
create policy "Admins can update receipts" on public.receipts for update to authenticated using(public.is_clean_scrub_admin()) with check(public.is_clean_scrub_admin());
